repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
        name: Clang Format
        args: [--style=file]
        files: \.(cpp|hpp|h|c|cc)$

  - repo: local
    hooks:
      - id: cppcheck
        name: Cppcheck
        entry: cppcheck --force --quiet --language=c++ --inline-suppr
        language: system
        types: [c, c++]
        files: \.(cpp|hpp|h|c|cc)$
